import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import CookieBanner from "@/components/cookie/CookieBanner";
import { JsonLd } from "@/components/seo/JsonLd";
import { organizationSchema, websiteSchema } from "@/lib/structured-data";
import { SITE_URL } from "@/lib/site";

// ─── Fonts ────────────────────────────────────────────────────────────────────
// next/font/local handles preloading, subsetting, and font-display automatically.
const gotham = localFont({
	src: [
		{
			path: "../../public/fonts/Gotham-Light.otf",
			weight: "300",
			style: "normal",
		},
		{
			path: "../../public/fonts/Gotham-Book.otf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../../public/fonts/Gotham-Medium.otf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../../public/fonts/Gotham-Bold.otf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../../public/fonts/Gotham-Black.otf",
			weight: "900",
			style: "normal",
		},
		{
			path: "../../public/fonts/Gotham-Ultra.otf",
			weight: "950",
			style: "normal",
		},
	],
	variable: "--font-gotham",
	display: "swap",
});

// ─── Viewport ─────────────────────────────────────────────────────────────────
export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	themeColor: "#130015",
};

// ─── Metadata ─────────────────────────────────────────────────────────────────
export const metadata: Metadata = {
	metadataBase: new URL(SITE_URL),

	title: {
		default: "OctiSight — Security from Insight to Action",
		template: "%s | OctiSight",
	},
	description:
		"OctiSight connects to your systems, maps vulnerabilities to your real stack, and delivers AI-powered remediation — so your business stays protected without needing a security team.",
	keywords: [
		"vulnerability management",
		"vulnerability management for small teams",
		"vulnerability scanning",
		"CVE prioritization",
		"CISA KEV",
		"EPSS",
		"AI remediation",
		"SBOM scanning",
		"dependency scanning",
		"CI/CD security",
		"SMB security",
	],
	authors: [{ name: "OctiSight", url: "https://octisight.com" }],

	openGraph: {
		type: "website",
		siteName: "OctiSight",
		url: "/",
		title: "OctiSight — Security from Insight to Action",
		description:
			"Real-time vulnerability mapping, AI remediation, and continuous monitoring for businesses of all sizes.",
		// og:image is generated by app/opengraph-image.tsx (don't set images here
		// or the static array would override the file convention).
	},

	twitter: {
		card: "summary_large_image",
		title: "OctiSight — Security from Insight to Action",
		description:
			"Real-time vulnerability mapping, AI remediation, and continuous monitoring.",
		// twitter:image is also derived from app/opengraph-image.tsx.
	},

	// Favicon / apple-touch icon come from app/icon.tsx + app/apple-icon.tsx.

	robots: {
		index: true,
		follow: true,
		googleBot: { index: true, follow: true, "max-snippet": -1 },
	},

	icons: {
		icon: '/images/logo/octisight-favicon-white.svg',  // ← Chemin depuis public/
	},
};

// ─── Layout ───────────────────────────────────────────────────────────────────
export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`scroll-smooth ${gotham.variable}`}>
			<body>
				{/* Skip link — first focusable element, jumps past the nav. */}
				<a
					href="#main-content"
					className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[100] focus:rounded-lg focus:bg-accent focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-white focus:shadow-lg focus:shadow-black/40"
				>
					Skip to main content
				</a>

				{/* Warm up the live-stats API origin (React 19 hoists these to <head>). */}
				<link rel="preconnect" href="https://api.octisight.io" />
				<link rel="dns-prefetch" href="https://api.octisight.io" />

				<JsonLd schema={[organizationSchema(), websiteSchema()]} />

				{children}
				<CookieBanner />
			</body>
		</html>
	);
}
